{
  pkgs,
  inputs,
  vars,
  ...
}:
let
  mkDirMode = directory: mode: { inherit directory mode; };
in
{
  imports = [
    inputs.preservation.nixosModules.default
  ];

  preservation.enable = true;
  # pverservation required initrd using systemd.
  boot.initrd.systemd.enable = true;

  environment.systemPackages = [
    # `sudo ncdu -x /`
    pkgs.ncdu
  ];

  # There are two ways to clear the root filesystem on every boot:
  ##  1. use tmpfs for /
  ##  2. (btrfs/zfs only)take a blank snapshot of the root filesystem and revert to it on every boot via:
  ##     boot.initrd.postDeviceCommands = ''
  ##       mkdir -p /run/mymount
  ##       mount -o subvol=/ /dev/disk/by-uuid/UUID /run/mymount
  ##       btrfs subvolume delete /run/mymount
  ##       btrfs subvolume snapshot / /run/mymount
  ##     '';
  #
  #  See also https://grahamc.com/blog/erase-your-darlings/

  # NOTE: preservation only mounts the directory/file list below to /persistent
  # If the directory/file already exists in the root filesystem you should
  # move those files/directories to /persistent first!
  preservation.preserveAt."/persistent" = {
    directories = [
      "/etc/NetworkManager/system-connections"
      "/etc/ssh"
      "/etc/nix/inputs"
      #       "/etc/nixos"

      # my secrets
      "/etc/agenix/"

      "/var/log"

      # system-core
      "/var/lib/nixos"
      "/var/lib/systemd"
      (mkDirMode "/var/lib/private" "0700")

      # lanzaboote - secure boot
      "/var/lib/sbctl"
      # fprintd fingerprint info
      (mkDirMode "/var/lib/fprint/" "0700")

      # containers
      "/var/lib/docker"
      "/var/lib/cni"
      "/var/lib/containers"

      # other data
      "/var/lib/flatpak"

      # virtualisation
      "/var/lib/libvirt"
      "/var/lib/lxc"
      "/var/lib/lxd"
      "/var/lib/qemu"
      # "/var/lib/waydroid"

      # network
      "/var/lib/tailscale"
      "/var/lib/bluetooth"
      "/var/lib/NetworkManager"
    ];

    files = [
      # auto-generated machine ID
      {
        file = "/etc/machine-id";
        inInitrd = true;
      }
      {
        file = "/etc/dae/config.dae";
        mode = "0600";
      }
    ];

    users."${vars.user.name}" = {
      commonMountOptions = [
        "x-gvfs-hide"
      ];
      directories = [
        # ======================================
        # XDG Directories
        # ======================================

        "Downloads"
        "Music"
        "Pictures"
        "Documents"
        "Videos"

        # ======================================
        # Nix / Home Manager Profiles
        # ======================================

        ".local/state/home-manager"
        ".local/state/nix/profiles"
        ".local/share/nix"

        # ======================================
        # IDE / Editors
        # ======================================
        ".config/imhex/config"
        ".idapro"

        # neovim plugins(wakatime & copilot)
        ".wakatime"
        ".config/github-copilot"

        # vscode
        ".vscode"
        ".config/Code"
        ".vscode-insiders"
        ".config/Code - Insiders"

        # cursor ai editor
        ".cursor"
        ".config/Cursor"

        # zed editor
        ".config/zed"
        ".local/share/zed"

        # nvim
        ".local/share/nvim"
        ".local/state/nvim"

        # ".local/share/jupyter"

        # ======================================
        # Cloud Native
        # ======================================
        (mkDirMode ".aws" "0700")
        (mkDirMode ".docker" "0700")

        # ======================================
        # language package managers
        # ======================================
        ".local/share/pnpm/store" # PNPM Store
        ".local/share/go" # Customized go path
        # ".npm" # typsescript/javascript
        # ".cargo" # rust
        # ".m2" # java maven
        # ".gradle" # java gradle
        # ".conda" # python generated by `conda-shell`

        # ======================================
        # Security
        # ======================================
        (mkDirMode ".gnupg" "0700")
        (mkDirMode ".ssh" "0700")
        (mkDirMode ".pki" "0700")
        (mkDirMode ".local/share/kwalletd" "0700")
        (mkDirMode ".local/share/networkmanagement" "0700")
        (mkDirMode ".config/Bitwarden" "0700")
        (mkDirMode ".local/share/password-store" "0700")

        # gnmome keyrings
        (mkDirMode ".local/share/keyrings" "0700")

        # ======================================
        # Instant Messaging
        # ======================================
        ".config/QQ"
        ".local/share/TelegramDesktop"

        # ======================================
        # Meeting / Remote Desktop
        # ======================================
        ".config/remmina"
        ".config/freerdp"
        ".local/share/remmina"

        # ======================================
        # browsers
        # ======================================
        (mkDirMode ".mozilla/firefox/dev-edition-default" "0700")
        (mkDirMode ".config/chromium" "0700")

        # ======================================
        # CLI data
        # ======================================
        ".local/share/atuin"
        ".local/share/direnv"
        ".local/share/k9s"

        # ======================================
        # Containers
        # ======================================
        ".local/share/containers"
        ".local/share/flatpak"
        # flatpak app's data
        ".var"

        # ======================================
        # Misc
        # ======================================

        # Audio
        ".config/pulse"
        ".local/state/wireplumber"
        ".local/share/netease-cloud-music-gtk4"
      ];
      files = [
        {
          file = ".wakatime.cfg";
          how = "symlink";
        }
        {
          file = ".config/kwinoutputconfig.json";
          how = "symlink";
        }

      ];
    };
  };

  # systemd-machine-id-commit.service would fail but it is not relevant
  # in this specific setup for a persistent machine-id so we disable it
  #
  # see the firstboot example below for an alternative approach
  systemd.suppressedSystemUnits = [ "systemd-machine-id-commit.service" ];

  # let the service commit the transient ID to the persistent volume
  systemd.services.systemd-machine-id-commit = {
    unitConfig.ConditionPathIsMountPoint = [
      ""
      "/persistent/etc/machine-id"
    ];
    serviceConfig.ExecStart = [
      ""
      "systemd-machine-id-setup --commit --root /persistent"
    ];
  };
}
