name: NixOS Build
description: Build NixOS system closure with caching

inputs:
  niks3-server-url:
    description: The URL of the Niks3 server
    required: true

runs:
  using: "composite"
  steps:
    - name: Apply Nix Settings
      shell: bash
      run: |
        nix build .#nix-conf
        cat ./result | sudo tee -a /etc/nix/nix.custom.conf
        sudo systemctl restart nix-daemon.service
    - name: Setup NikS3
      shell: bash
      run: |
        nix profile install "github:Mic92/niks3"
    - name: Write Cache Credentials
      id: write-cache-credentials
      shell: bash
      env:
        NIKS3_SERVER_URL: ${{ inputs.niks3-server-url }}
      run: |
        hook_location=$(mktemp '/tmp/post-build-hook.XXXXXXXXXX.py')
        sed -e "s|@@EXTRA_PATHS@@|$PATH|g" \
            -e "s|@@NIKS3_SERVER_URL@@|$NIKS3_SERVER_URL|g" \
            -e "s|@@ACTIONS_ID_TOKEN_REQUEST_TOKEN@@|$ACTIONS_ID_TOKEN_REQUEST_TOKEN|g" \
            -e "s|@@ACTIONS_ID_TOKEN_REQUEST_URL@@|$ACTIONS_ID_TOKEN_REQUEST_URL|g" \
            "${GITHUB_ACTION_PATH}/post-build-hook.py" > "$hook_location"
        chmod +x "$hook_location"
        echo "post-build-hook=$hook_location" >> "$GITHUB_OUTPUT"
    - name: Run Nix Build
      shell: bash
      env:
        POST_BUILD_HOOK: ${{ steps.write-cache-credentials.outputs.post-build-hook }}
      run: |
        nix build ".#toplevel" \
          --fallback \
          --print-build-logs \
          --option post-build-hook "${POST_BUILD_HOOK}"
