name: NixOS Build
description: Build NixOS system closure with caching
inputs:
  niks3-server-url:
    description: The URL of the Niks3 server
    required: true
runs:
  using: "composite"
  steps:
    - uses: Mic92/niks3-action@main
      with:
        server-url: ${{ inputs.niks3-server-url }}
    - name: Apply Nix Settings
      shell: bash
      run: |
        nix build .#nix-conf
        mkdir -p ~/.config/nix
        cat ./result | tee -a ~/.config/nix/nix.conf
    - name: Restart Nix Daemon on Linux
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo systemctl restart nix-daemon.service
    - name: Restart Nix Daemon on macOS
      shell: bash
      if: runner.os == 'macOS'
      run: |
        sudo launchctl kickstart -k system/org.nixos.nix-daemon
    - name: Run Nix Build
      shell: bash
      run: |
        nix build ".#toplevel" \
          --fallback \
          --print-build-logs
