name: Setup Nix
description: Setup Nix with caching

inputs:
  free-space:
    description: Whether to free space before building
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - uses: wimpysworld/nothing-but-nix@main
      if: inputs.free-space == 'true'
      with:
        hatchet-protocol: rampage
        mnt-safe-haven: 6144
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        diagnostic-endpoint: ""
    - name: Workaround AppArmor # https://git.lix.systems/lix-project/lix/issues/545
      shell: bash
      run: |
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
