name: Nix Build CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "scripts/**"
      - "**.md"
      - "**.nu"
      - "Justfile"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "scripts/**"
      - "**.md"
      - "**.nu"
      - "Justfile"
jobs:
  checks:
    name: Check build
    strategy:
      matrix:
        include:
          - hostname: mix-laptop-21tl
            os: ubuntu-latest
          - hostname: mix-moonshot
            os: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/nixos-build
        with:
          hostname: ${{ matrix.hostname }}
          niks3-server-url: ${{ secrets.NIKS3_SERVER_URL }}
