name: Cache Garbage Collection
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  gc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      NIKS3_SERVER_URL: ${{ secrets.NIKS3_SERVER_URL }}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          free-space: false
      - uses: Mic92/niks3-action@main
        id: niks3
        with:
          server-url: ${{ secrets.NIKS3_SERVER_URL }}
      - name: Garbage Collect
        run: |
          "${{ steps.niks3.outputs.binary-dir }}/niks3" gc \
            --older-than 168h \
            --auth-token-script "${{ steps.niks3.outputs.auth-token-script }}"
